Repository palantir/python-compute-module, pull requests merged in 2024-10, with the labels that each got.

#2 Include job ID & process ID in logger context
  DEV_SETUP.md
  README.md
  changelog/@unreleased/pr-2.v2.yml
  compute_modules/client/internal_query_client.py
  compute_modules/function_registry/function_payload_converter.py
  compute_modules/logging/__init__.py
  compute_modules/logging/common.py
  compute_modules/logging/internal.py
  compute_modules/logging/public.py
  tests/logging/logging_test_utils.py
  tests/logging/test_log_context.py
  tests/logging/test_log_levels.py
Labels: autorelease

#4 Add static typing for QueryContext param
  README.md
  changelog/@unreleased/pr-4.v2.yml
  compute_modules/__init__.py
  compute_modules/client/internal_query_client.py
  compute_modules/context/__init__.py
  compute_modules/context/context.py
  compute_modules/context/types.py
  compute_modules/function_registry/function_payload_converter.py
  compute_modules/function_registry/function_registry.py
  compute_modules/function_registry/function_schema_parser.py
  compute_modules/function_registry/types.py
  compute_modules/startup.py
  tests/function_registry/dummy_app.py
  tests/function_registry/test_function_payload_converter.py
  tests/function_registry/test_function_schema_parser.py
Labels: autorelease, merge when ready

#5 Handle Unknown output datatype with string as default
  changelog/@unreleased/pr-5.v2.yml
  compute_modules/function_registry/function_schema_parser.py
  tests/function_registry/test_function_schema_parser.py
Labels: do not merge

#7 Raise error early on dict with no type params
  README.md
  changelog/@unreleased/pr-7.v2.yml
  compute_modules/function_registry/function_schema_parser.py
  tests/function_registry/dummy_app.py
  tests/function_registry/test_function_schema_parser.py
Labels: autorelease, do not merge

#9 Rename LINCENSE -> LICENSE.txt
  LICENSE.txt
  changelog/@unreleased/pr-9.v2.yml
  scripts/checks.py
Labels: autorelease

#10 force encoding to be utf-8
  changelog/@unreleased/pr-10.v2.yml
  compute_modules/auth/pipeline.py
  compute_modules/client/internal_query_client.py
  compute_modules/resources/pipeline_resources.py
  compute_modules/sources.py
  scripts/checks.py
  scripts/set_version.py
Labels: autorelease

#12 set_version error poetry cmd
  .circleci/config.yml
  changelog/@unreleased/pr-12.v2.yml
Labels: autorelease

#15 Add streaming support for iterable result
  README.md
  changelog/@unreleased/pr-15.v2.yml
  compute_modules/annotations.py
  compute_modules/client/internal_query_client.py
  compute_modules/function_registry/function_registry.py
  compute_modules/function_registry/function_schema_parser.py
  compute_modules/startup.py
  tests/function_registry/dummy_app.py
  tests/function_registry/test_function_schema_parser.py
Labels: autorelease, merge when ready
