Repository palantir/python-compute-module, pull requests merged in 2025-03, with the labels that each got.

#24 add CLI for running schema inference at build time
  LICENSE.txt
  changelog/@unreleased/pr-24.v2.yml
  compute_modules/annotations.py
  compute_modules/bin/__init__.py
  compute_modules/client/internal_query_client.py
  compute_modules/function_registry/function.py
  compute_modules/function_registry/function_registry.py
  compute_modules/function_registry/function_schema_parser.py
  compute_modules/startup.py
  pyproject.toml
  scripts/checks.py
  scripts/infer/__init__.py
  scripts/infer/infer.py
  scripts/infer/main.py
  tests/infer/__init__.py
  tests/infer/test_infer.py
  tests/infer/test_project/__init__.py
  tests/infer/test_project/_types.py
  tests/infer/test_project/decorated/__init__.py
  tests/infer/test_project/decorated/alias_types.py
  tests/infer/test_project/decorated/collection_types.py
  tests/infer/test_project/decorated/primitive_types.py
  tests/infer/test_project/manually_registered/__init__.py
  tests/infer/test_project/manually_registered/mixed_registration.py
  tests/infer/test_project/manually_registered/multiple_functions.py
  tests/infer/test_project/manually_registered/single_function.py
  tests/infer/test_project/manually_registered/unguarded_single_function.py
Labels: autorelease, merge when ready

#28 [Connectivity] Support mounted source config
  README.md
  changelog/@unreleased/pr-28.v2.yml
  compute_modules/context/context.py
  compute_modules/sources.py
Labels: autorelease, merge when ready, 🤖 fix nits

#29 Fix missing kwargs in query context
  changelog/@unreleased/pr-29.v2.yml
  compute_modules/context/types.py
Labels: autorelease, merge when ready

#30 Add refreshing oauth token
  README.md
  changelog/@unreleased/pr-30.v2.yml
  compute_modules/auth/third_party.py
  tests/auth/test_third_party.py
Labels: do not merge
