Repository palantir/python-compute-module, pull requests merged in 2025-04, with the labels that each got.

#31 fix silent error raised when executing unknown query
  changelog/@unreleased/pr-31.v2.yml
  compute_modules/client/internal_query_client.py
Labels: merge when ready

#27 Add installable scripts for static function inference
  changelog/@unreleased/pr-24.v2.yml
  compute_modules/bin/ontology/__init__.py
  compute_modules/bin/ontology/_config_path.py
  compute_modules/bin/ontology/_types.py
  compute_modules/bin/ontology/generate_metadata_config.py
  compute_modules/bin/ontology/metadata_client.py
  compute_modules/bin/ontology/metadata_loader.py
  compute_modules/bin/static_inference/__init__.py
  compute_modules/bin/static_inference/infer.py
  pyproject.toml
  scripts/infer/main.py
  tests/infer/test_infer.py
Labels: autorelease, merge when ready

#32 [Connectivity] Source interface in Compute Modules Lib
  .circleci/config.yml
  DEV_SETUP.md
  README.md
  changelog/@unreleased/pr-32.v2.yml
  compute_modules/context/context.py
  compute_modules/sources/__init__.py
  compute_modules/sources/_sources.py
  compute_modules/sources_v2/__init__.py
  compute_modules/sources_v2/_api.py
  compute_modules/sources_v2/_back_compat.py
  compute_modules/sources_v2/_sources.py
  pyproject.toml
  tests/sources_v2/test_sources.py
Labels: autorelease, 🤖 fix nits
